name: Static Analysis for All Commits
on:
  push:
    branches:
      - '*'
jobs:
  build:
    name: Golang Formatter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
      with:
        fetch-depth: 0
    - name: format code
      run: |
        gofmt -s .
    - name: tidy up
      run: |
        go mod tidy
    - name: lint the code
      run: |
        go get golang.org/x/lint/golint
        go install golang.org/x/lint/golint
        golint ./...


