name: Golang Formatter
on:
  push:
    branches:
      - '*'
jobs:
  build:
    name: Golang Formatter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
      with:
        fetch-depth: 0
    - name: tidy up
      run: |
        go mod tidy
    - name: lint the code
      run: |
        go get -u github.com/golang/lint/golint
        golint ./...


